# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-PayPal-WPP-ExpressCheckout
version:      0.05
version_from: lib/Business/PayPal/WPP/ExpressCheckout.pm
installdirs:  vendor
requires:
    SOAP::Lite:                    0.67

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
